"""create tables in my_schema

Revision ID: 3393ff7b25af
Revises: 
Create Date: 2025-08-19 19:15:27.067067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3393ff7b25af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number'),
    schema='AxisMD'
    )
    op.create_index(op.f('ix_AxisMD_users_email'), 'users', ['email'], unique=True, schema='AxisMD')
    op.create_index(op.f('ix_AxisMD_users_id'), 'users', ['id'], unique=False, schema='AxisMD')
    op.create_index(op.f('ix_AxisMD_users_username'), 'users', ['username'], unique=True, schema='AxisMD')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_AxisMD_users_username'), table_name='users', schema='AxisMD')
    op.drop_index(op.f('ix_AxisMD_users_id'), table_name='users', schema='AxisMD')
    op.drop_index(op.f('ix_AxisMD_users_email'), table_name='users', schema='AxisMD')
    op.drop_table('users', schema='AxisMD')
    # ### end Alembic commands ###
